[package]
name = "flex_net_tcp"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { workspace = true }
anyhow = { workspace = true }
flex_net_core = { path = "../flex_net_core" }
tokio-tls = { workspace = true }
native-tls = { workspace = true }
tokio-native-tls = { workspace = true }
