[package]
name = "flex_server_core"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
tokio = { workspace = true }
log = { workspace = true }
futures = { workspace = true }
flex_net_core = { path = "../flex_net_core" }
